-- 코드를 입력하세요
SELECT Info.REST_ID, Info.REST_NAME, Info.FOOD_TYPE, Info.FAVORITES, Info.ADDRESS, ROUND(AVG(Review.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO as Info
Join REST_REVIEW as Review on Info.REST_ID = Review.REST_ID
WHERE SUBSTRING(Info.ADDRESS, 1, 2) = '서울'
Group by REST_ID
ORDER BY SCORE DESC, Info.FAVORITES DESC
